### ISSUE TITLE
NATS does nothing when running in a fastapi app

### ISSUE THREAD

**Issue by jmwielandt** [nats-io/nats.py#432]
Let's avoid XY problem.

## My problem
- I need a web server that exposes an HTTP api + websocket for a multiplatform client (can't be changed).
- Some data are stored in other service and is requested via HTTP (can't be changed).
- Other data is sent via NATS (can't be changed) in an express route to this web server so is as "realtime" as it can be.
- Multiplatform clients can't listen directly to NATS (can't be changed).

## My solution:

1. Build a fastapi server and add some callbacks for NATS.
2. Each time one of those callbacks are triggered, I modify the inner state of the server so the new data is available for the client to request (notified via websocket; Yes, I could send the data directly through the websocket but that doesn't matters here). 

### Setup
Here I define a main function which is called by uvicorn on the CLI, and a startup function which is called by the startup event on fastapi.
![imagen](https://user-images.githubusercontent.com/37153467/224722556-b9af08a2-bd62-47e9-a767-f497c1228891.png)

This is how I open the NATS connection and add my callback. For now is a very simple thing.
![imagen](https://user-images.githubusercontent.com/37153467/224722923-678c91b0-a503-41c2-a65a-69054d3c9261.png)

This is my create_app function. I'm using the decorator by hand on this so I can define its behavior alongside all other tear up definitions.
![imagen](https://user-images.githubusercontent.com/37153467/224723335-316009d2-2516-4c89-a6c2-55f2b4034e02.png)

### Expected

Each time I got a NATS message a print appears on the console.

### Actual behavior

The callback is never called.

Here you can see the actual command I'm using to run the whole thing.
![imagen](https://user-images.githubusercontent.com/37153467/224724070-bbd73c53-691d-459b-a5b3-8ea84832227c.png)

### Environment
- Dependencies:
    ```toml
    [tool.poetry.dependencies]
    python = "^3.10"
    toml = "^0.10.2"
    requests = "^2.28.2"
    fastapi = {extras = ["uvicorn"], version = "^0.93.0"}
    colorama = "^0.4.6"
    redis = "^4.5.1"
    rfc3339 = "^6.2"
    iso8601 = "^1.1.0"
    dynaconf = "^3.1.12"
    minio = "^7.1.13"
    bidict = "^0.22.1"
    pyjson5 = "^1.6.2"
    strenum = "^0.4.9"
    uvicorn = {extras = ["standard"], version = "^0.21.0"}
    nats-py = "^2.2.0"
    ```
- Python version: 3.10.8
- OS: windows 10
- Poetry version: 1.2.2
